# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, choices=[('DEV', 'Development'), ('HW', 'Homework'), ('EDU', 'Educational'), ('DOCS', 'Non-educational'), ('WEB', 'Web'), ('DATA', 'Data'), ('OTHER', 'Other')], max_length=10)),
            ],
        ),
    ]
