# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_auto_20161220_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.Repository')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='feature',
            unique_together=set([('repository', 'name')]),
        ),
    ]
