# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0003_auto_20161229_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
