# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0004_auto_20170106_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='value',
            field=models.FloatField(default=0.0),
        ),
    ]
